# Generated by Django 5.1.2 on 2024-12-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burnout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurnoutForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=100)),
                ('doj', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('company_type', models.CharField(max_length=10)),
                ('wfh_setup', models.CharField(max_length=3)),
                ('designation', models.IntegerField()),
                ('resources', models.IntegerField()),
                ('mental_fatigue', models.FloatField()),
            ],
        ),
    ]
