# Generated by Django 5.1.2 on 2024-12-22 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burnout', '0002_burnoutform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='burnoutform',
            old_name='doj',
            new_name='date_of_joining',
        ),
        migrations.RenameField(
            model_name='burnoutform',
            old_name='mental_fatigue',
            new_name='mental_fatigue_score',
        ),
        migrations.RenameField(
            model_name='burnoutform',
            old_name='resources',
            new_name='resources_allocation',
        ),
    ]
